name: campus_guide_ai
description: An AI-powered campus guide application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.1
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/CGAI_logo.png
    - assets/images/USTP.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/static/Montserrat-Regular.ttf
        - asset: assets/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/static/Montserrat-Bold.ttf
          weight: 700

